(function(factory){var jQuery;if(typeof exports==="object"){try{jQuery=require("jquery");}catch(e){}
module.exports=factory(window,document,jQuery);}else if(typeof define==='function'&&define.amd){define([],function(){return factory(window,document,window.jQuery)});}else{window.Dropkick=factory(window,document,window.jQuery);}}(function(window,document,jQuery,undefined){var
isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),isIframe=window.parent!==window.self,isIE=navigator.appVersion.indexOf("MSIE")!==-1,Dropkick=function(sel,opts){var i,dk;if(this===window){return new Dropkick(sel,opts);}
if(typeof sel==="string"&&sel[0]==="#"){sel=document.getElementById(sel.substr(1));}
for(i=0;i<Dropkick.uid;i++){dk=Dropkick.cache[i];if(dk instanceof Dropkick&&dk.data.select===sel){_.extend(dk.data.settings,opts);return dk;}}
if(!sel){console.error("You must pass a select to DropKick");return false;}
if(sel.length<1){console.error("You must have options inside your <select>: ",sel);return false;}
if(sel.nodeName==="SELECT"){return this.init(sel,opts);}},noop=function(){},_docListener,defaults={initialize:noop,mobile:false,change:noop,open:noop,close:noop,search:"strict",bubble:true},_={hasClass:function(elem,classname){var reg=new RegExp("(^|\\s+)"+classname+"(\\s+|$)");return elem&&reg.test(elem.className);},addClass:function(elem,classname){if(elem&&!_.hasClass(elem,classname)){elem.className+=" "+classname;}},removeClass:function(elem,classname){var reg=new RegExp("(^|\\s+)"+classname+"(\\s+|$)");elem&&(elem.className=elem.className.replace(reg," "));},toggleClass:function(elem,classname){var fn=_.hasClass(elem,classname)?"remove":"add";_[fn+"Class"](elem,classname);},extend:function(obj){Array.prototype.slice.call(arguments,1).forEach(function(source){if(source){for(var prop in source)obj[prop]=source[prop];}});return obj;},offset:function(elem){var box=elem.getBoundingClientRect()||{top:0,left:0},docElem=document.documentElement,offsetTop=isIE?docElem.scrollTop:window.pageYOffset,offsetLeft=isIE?docElem.scrollLeft:window.pageXOffset;return{top:box.top+offsetTop-docElem.clientTop,left:box.left+offsetLeft-docElem.clientLeft};},position:function(elem,relative){var pos={top:0,left:0};while(elem&&elem!==relative){pos.top+=elem.offsetTop;pos.left+=elem.offsetLeft;elem=elem.parentNode;}
return pos;},closest:function(child,ancestor){while(child){if(child===ancestor){return child;}
child=child.parentNode;}
return false;},create:function(name,attrs){var a,node=document.createElement(name);if(!attrs){attrs={};}
for(a in attrs){if(attrs.hasOwnProperty(a)){if(a==="innerHTML"){node.innerHTML=attrs[a];}else{node.setAttribute(a,attrs[a]);}}}
return node;},deferred:function(fn){return function(){var args=arguments,ctx=this;window.setTimeout(function(){fn.apply(ctx,args);},1);};}};Dropkick.cache={};Dropkick.uid=0;Dropkick.prototype={add:function(elem,before){var text,option,i;if(typeof elem==="string"){text=elem;elem=document.createElement("option");elem.text=text;}
if(elem.nodeName==="OPTION"){option=_.create("li",{"class":"dk-option","data-value":elem.value,"innerHTML":elem.text,"role":"option","aria-selected":"false","id":"dk"+this.data.cacheID+"-"+(elem.id||elem.value.replace(" ","-"))});_.addClass(option,elem.className);this.length+=1;if(elem.disabled){_.addClass(option,"dk-option-disabled");option.setAttribute("aria-disabled","true");}
if(elem.hidden){_.addClass(option,"dk-option-hidden");option.setAttribute("aria-hidden","true");}
this.data.select.add(elem,before);if(typeof before==="number"){before=this.item(before);}
i=this.options.indexOf(before);if(i>-1){before.parentNode.insertBefore(option,before);this.options.splice(i,0,option);}else{this.data.elem.lastChild.appendChild(option);this.options.push(option);}
option.addEventListener("mouseover",this);if(elem.selected){this.select(i);}}},item:function(index){index=index<0?this.options.length+index:index;return this.options[index]||null;},remove:function(index){var dkOption=this.item(index);dkOption.parentNode.removeChild(dkOption);this.options.splice(index,1);this.data.select.remove(index);this.select(this.data.select.selectedIndex);this.length-=1;},init:function(sel,opts){var i,dk=Dropkick.build(sel,"dk"+Dropkick.uid);this.data={};this.data.select=sel;this.data.elem=dk.elem;this.data.settings=_.extend({},defaults,opts);this.disabled=sel.disabled;this.form=sel.form;this.length=sel.length;this.multiple=sel.multiple;this.options=dk.options.slice(0);this.selectedIndex=sel.selectedIndex;this.selectedOptions=dk.selected.slice(0);this.value=sel.value;this.data.cacheID=Dropkick.uid;Dropkick.cache[this.data.cacheID]=this;this.data.settings.initialize.call(this);Dropkick.uid+=1;if(!this._changeListener){sel.addEventListener("change",this);this._changeListener=true;}
if(!(isMobile&&!this.data.settings.mobile)){sel.parentNode.insertBefore(this.data.elem,sel);sel.setAttribute("data-dkCacheId",this.data.cacheID);this.data.elem.addEventListener("click",this);this.data.elem.addEventListener("keydown",this);this.data.elem.addEventListener("keypress",this);if(this.form){this.form.addEventListener("reset",this);}
if(!this.multiple){for(i=0;i<this.options.length;i++){this.options[i].addEventListener("mouseover",this);}}
if(!_docListener){document.addEventListener("click",Dropkick.onDocClick);if(isIframe){parent.document.addEventListener("click",Dropkick.onDocClick);}
_docListener=true;}}
return this;},close:function(){var i,dk=this.data.elem;if(!this.isOpen||this.multiple){return false;}
for(i=0;i<this.options.length;i++){_.removeClass(this.options[i],"dk-option-highlight");}
dk.lastChild.setAttribute("aria-expanded","false");_.removeClass(dk.lastChild,"dk-select-options-highlight");_.removeClass(dk,"dk-select-open-(up|down)");this.isOpen=false;this.data.settings.close.call(this);},open:_.deferred(function(){var dropHeight,above,below,direction,dkTop,dkBottom,dk=this.data.elem,dkOptsList=dk.lastChild,supportPageOffset=window.pageXOffset!==undefined,isCSS1Compat=((document.compatMode||"")==="CSS1Compat"),scrollY=supportPageOffset?window.pageYOffset:isCSS1Compat?document.documentElement.scrollTop:document.body.scrollTop;dkTop=_.offset(dk).top-scrollY;dkBottom=window.innerHeight-(dkTop+dk.offsetHeight);if(this.isOpen||this.multiple){return false;}
dkOptsList.style.display="block";dropHeight=dkOptsList.offsetHeight;dkOptsList.style.display="";above=dkTop>dropHeight;below=dkBottom>dropHeight;direction=above&&!below?"-up":"-down";this.isOpen=true;_.addClass(dk,"dk-select-open"+direction);dkOptsList.setAttribute("aria-expanded","true");this._scrollTo(this.options.length-1);this._scrollTo(this.selectedIndex);this.data.settings.open.call(this);}),disable:function(elem,disabled){var disabledClass="dk-option-disabled";if(arguments.length===0||typeof elem==="boolean"){disabled=elem===undefined?true:false;elem=this.data.elem;disabledClass="dk-select-disabled";this.disabled=disabled;}
if(disabled===undefined){disabled=true;}
if(typeof elem==="number"){elem=this.item(elem);}
if(disabled){elem.setAttribute('aria-disabled',true);_.addClass(elem,disabledClass);}else{elem.setAttribute('aria-disabled',false);_.removeClass(elem,disabledClass);}},hide:function(elem,hidden){var hiddenClass="dk-option-hidden";if(hidden===undefined){hidden=true;}
elem=this.item(elem);if(hidden){elem.setAttribute('aria-hidden',true);_.addClass(elem,hiddenClass);}else{elem.setAttribute('aria-hidden',false);_.removeClass(elem,hiddenClass);}},select:function(elem,disabled){var i,index,option,combobox,select=this.data.select;if(typeof elem==="number"){elem=this.item(elem);}
if(typeof elem==="string"){for(i=0;i<this.length;i++){if(this.options[i].getAttribute("data-value")===elem){elem=this.options[i];}}}
if(!elem||typeof elem==="string"||(!disabled&&_.hasClass(elem,"dk-option-disabled"))){return false;}
if(_.hasClass(elem,"dk-option")){index=this.options.indexOf(elem);option=select.options[index];if(this.multiple){_.toggleClass(elem,"dk-option-selected");option.selected=!option.selected;if(_.hasClass(elem,"dk-option-selected")){elem.setAttribute("aria-selected","true");this.selectedOptions.push(elem);}else{elem.setAttribute("aria-selected","false");index=this.selectedOptions.indexOf(elem);this.selectedOptions.splice(index,1);}}else{combobox=this.data.elem.firstChild;if(this.selectedOptions.length){_.removeClass(this.selectedOptions[0],"dk-option-selected");this.selectedOptions[0].setAttribute("aria-selected","false");}
_.addClass(elem,"dk-option-selected");elem.setAttribute("aria-selected","true");combobox.setAttribute("aria-activedescendant",elem.id);combobox.className="dk-selected "+option.className;combobox.innerHTML=option.text;this.selectedOptions[0]=elem;option.selected=true;}
this.selectedIndex=select.selectedIndex;this.value=select.value;if(!disabled){this.data.select.dispatchEvent(new CustomEvent("change",{bubbles:this.data.settings.bubble}));}
return elem;}},selectOne:function(elem,disabled){this.reset(true);this._scrollTo(elem);return this.select(elem,disabled);},search:function(pattern,mode){var i,tokens,str,tIndex,sIndex,cScore,tScore,reg,options=this.data.select.options,matches=[];if(!pattern){return this.options;}
mode=mode?mode.toLowerCase():"strict";mode=mode==="fuzzy"?2:mode==="partial"?1:0;reg=new RegExp((mode?"":"^")+pattern,"i");for(i=0;i<options.length;i++){str=options[i].text.toLowerCase();if(mode==2){tokens=pattern.toLowerCase().split("");tIndex=sIndex=cScore=tScore=0;while(sIndex<str.length){if(str[sIndex]===tokens[tIndex]){cScore+=1+cScore;tIndex++;}else{cScore=0;}
tScore+=cScore;sIndex++;}
if(tIndex===tokens.length){matches.push({e:this.options[i],s:tScore,i:i});}}else{reg.test(str)&&matches.push(this.options[i]);}}
if(mode===2){matches=matches.sort(function(a,b){return(b.s-a.s)||a.i-b.i;}).reduce(function(p,o){p[p.length]=o.e;return p;},[]);}
return matches;},focus:function(){if(!this.disabled){(this.multiple?this.data.elem:this.data.elem.children[0]).focus();}},reset:function(clear){var i,select=this.data.select;this.selectedOptions.length=0;for(i=0;i<select.options.length;i++){select.options[i].selected=false;_.removeClass(this.options[i],"dk-option-selected");this.options[i].setAttribute("aria-selected","false");if(!clear&&select.options[i].defaultSelected){this.select(i,true);}}
if(!this.selectedOptions.length&&!this.multiple){this.select(0,true);}},refresh:function(){if(Object.keys(this).length>0&&!(isMobile&&!this.data.settings.mobile)){this.dispose().init(this.data.select,this.data.settings);}},dispose:function(){if(Object.keys(this).length>0&&!(isMobile&&!this.data.settings.mobile)){delete Dropkick.cache[this.data.cacheID];this.data.elem.parentNode.removeChild(this.data.elem);this.data.select.removeAttribute("data-dkCacheId");}
return this;},handleEvent:function(event){if(this.disabled){return;}
switch(event.type){case"click":this._delegate(event);break;case"keydown":this._keyHandler(event);break;case"keypress":this._searchOptions(event);break;case"mouseover":this._highlight(event);break;case"reset":this.reset();break;case"change":this.data.settings.change.call(this);break;}},_delegate:function(event){var selection,index,firstIndex,lastIndex,target=event.target;if(_.hasClass(target,"dk-option-disabled")){return false;}
if(!this.multiple){this[this.isOpen?"close":"open"]();if(_.hasClass(target,"dk-option")){this.select(target);}}else{if(_.hasClass(target,"dk-option")){selection=window.getSelection();if(selection.type==="Range")selection.collapseToStart();if(event.shiftKey){firstIndex=this.options.indexOf(this.selectedOptions[0]);lastIndex=this.options.indexOf(this.selectedOptions[this.selectedOptions.length-1]);index=this.options.indexOf(target);if(index>firstIndex&&index<lastIndex)index=firstIndex;if(index>lastIndex&&lastIndex>firstIndex)lastIndex=firstIndex;this.reset(true);if(lastIndex>index){while(index<lastIndex+1){this.select(index++);}}else{while(index>lastIndex-1){this.select(index--);}}}else if(event.ctrlKey||event.metaKey){this.select(target);}else{this.reset(true);this.select(target);}}}},_highlight:function(event){var i,option=event.target;if(!this.multiple){for(i=0;i<this.options.length;i++){_.removeClass(this.options[i],"dk-option-highlight");}
_.addClass(this.data.elem.lastChild,"dk-select-options-highlight");_.addClass(option,"dk-option-highlight");}},_keyHandler:function(event){var lastSelected,j,selected=this.selectedOptions,options=this.options,i=1,keys={tab:9,enter:13,esc:27,space:32,up:38,down:40};switch(event.keyCode){case keys.up:i=-1;case keys.down:event.preventDefault();lastSelected=selected[selected.length-1];if(_.hasClass(this.data.elem.lastChild,"dk-select-options-highlight")){_.removeClass(this.data.elem.lastChild,"dk-select-options-highlight");for(j=0;j<options.length;j++){if(_.hasClass(options[j],"dk-option-highlight")){_.removeClass(options[j],"dk-option-highlight");lastSelected=options[j];}}}
i=options.indexOf(lastSelected)+i;if(i>options.length-1){i=options.length-1;}else if(i<0){i=0;}
if(!this.data.select.options[i].disabled){this.reset(true);this.select(i);this._scrollTo(i);}
break;case keys.space:if(!this.isOpen){event.preventDefault();this.open();break;}
case keys.tab:case keys.enter:for(i=0;i<options.length;i++){if(_.hasClass(options[i],"dk-option-highlight")){this.select(i);}}
case keys.esc:if(this.isOpen){event.preventDefault();this.close();}
break;}},_searchOptions:function(event){var results,self=this,keyChar=String.fromCharCode(event.keyCode||event.which),waitToReset=function(){if(self.data.searchTimeout){clearTimeout(self.data.searchTimeout);}
self.data.searchTimeout=setTimeout(function(){self.data.searchString="";},1000);};if(this.data.searchString===undefined){this.data.searchString="";}
waitToReset();this.data.searchString+=keyChar;results=this.search(this.data.searchString,this.data.settings.search);if(results.length){if(!_.hasClass(results[0],"dk-option-disabled")){this.selectOne(results[0]);}}},_scrollTo:function(option){var optPos,optTop,optBottom,dkOpts=this.data.elem.lastChild;if(option===-1||(typeof option!=="number"&&!option)||(!this.isOpen&&!this.multiple)){return false;}
if(typeof option==="number"){option=this.item(option);}
optPos=_.position(option,dkOpts).top;optTop=optPos-dkOpts.scrollTop;optBottom=optTop+option.offsetHeight;if(optBottom>dkOpts.offsetHeight){optPos+=option.offsetHeight;dkOpts.scrollTop=optPos-dkOpts.offsetHeight;}else if(optTop<0){dkOpts.scrollTop=optPos;}}};Dropkick.build=function(sel,idpre){var selOpt,optList,i,options=[],ret={elem:null,options:[],selected:[]},addOption=function(node){var option,optgroup,optgroupList,i,children=[];switch(node.nodeName){case"OPTION":option=_.create("li",{"class":"dk-option ","data-value":node.value,"innerHTML":node.text,"role":"option","aria-selected":"false","id":idpre+"-"+(node.id||node.value.replace(" ","-"))});_.addClass(option,node.className);if(node.disabled){_.addClass(option,"dk-option-disabled");option.setAttribute("aria-disabled","true");}
if(node.hidden){_.addClass(option,"dk-option-hidden");option.setAttribute("aria-hidden","true");}
if(node.selected){_.addClass(option,"dk-option-selected");option.setAttribute("aria-selected","true");ret.selected.push(option);}
ret.options.push(this.appendChild(option));break;case"OPTGROUP":optgroup=_.create("li",{"class":"dk-optgroup"});if(node.label){optgroup.appendChild(_.create("div",{"class":"dk-optgroup-label","innerHTML":node.label}));}
optgroupList=_.create("ul",{"class":"dk-optgroup-options"});for(i=node.children.length;i--;children.unshift(node.children[i]));children.forEach(addOption,optgroupList);this.appendChild(optgroup).appendChild(optgroupList);break;}};ret.elem=_.create("div",{"class":"dk-select"+(sel.multiple?"-multi":"")});optList=_.create("ul",{"class":"dk-select-options","id":idpre+"-listbox","role":"listbox"});if(sel.disabled){_.addClass(ret.elem,"dk-select-disabled");ret.elem.setAttribute('aria-disabled',true);}
ret.elem.id=idpre+(sel.id?"-"+sel.id:"");_.addClass(ret.elem,sel.className);if(!sel.multiple){selOpt=sel.options[sel.selectedIndex];ret.elem.appendChild(_.create("div",{"class":"dk-selected "+selOpt.className,"tabindex":sel.tabindex||0,"innerHTML":selOpt?selOpt.text:'&nbsp;',"id":idpre+"-combobox","aria-live":"assertive","aria-owns":optList.id,"role":"combobox"}));optList.setAttribute("aria-expanded","false");}else{ret.elem.setAttribute("tabindex",sel.getAttribute("tabindex")||"0");optList.setAttribute("aria-multiselectable","true");}
for(i=sel.children.length;i--;options.unshift(sel.children[i]));options.forEach(addOption,ret.elem.appendChild(optList));return ret;};Dropkick.onDocClick=function(event){var tId,i;if(event.target.nodeType!==1){return false;}
if((tId=event.target.getAttribute("data-dkcacheid"))!==null){Dropkick.cache[tId].focus();}
for(i in Dropkick.cache){if(!_.closest(event.target,Dropkick.cache[i].data.elem)&&i!==tId){Dropkick.cache[i].disabled||Dropkick.cache[i].close();}}};if(jQuery!==undefined){jQuery.fn.dropkick=function(){var args=Array.prototype.slice.call(arguments);return jQuery(this).each(function(){if(!args[0]||typeof args[0]==='object'){new Dropkick(this,args[0]||{});}else if(typeof args[0]==='string'){Dropkick.prototype[args[0]].apply(new Dropkick(this),args.slice(1));}});};}
return Dropkick;}));